### ISSUE TITLE
Script for doing LGF updates with LAMMPS

### ISSUE THREAD

**Issue by aztan2** [TrinkleGroup/LatticeGreenFunction_new#1]
As of 8/15/2018: working on a python script that automates alternating between performing core relaxations with LAMMPS and applying LGF updates. Basically, this should work similarly to the LGF patch for VASP.

**Comment by aztan2** [comment]
it seems that the issue causing the most confusion is the inconsistency between the scaling of the atom mnt coords in `grid` and in the lammps `.data` input file. The original idea to have the atom coords in `grid` scaled out by the lattice constant a0 was a legacy of other scripts where doing so helped with comparisons between pair vectors when performing neighbor searches. However, for scripts that primarily interface with lammps, this seems to be more clunky than helpful. Probably the most sensible thing to do would be to keep the coords in `grid` in Angstroms throughout, and get rid of the a0 scaling in the IO_lammps.py functions.

**Comment by DallasTrinkle** [comment]
I'm not sure what the best approach is here. When working with `VASP`, there's an argument for using scaled coordinates. However, I'm not sure how helpful that is--we only end up producing a `POSCAR` file at the very end. Having a workable `LAMMPS` interface seems useful to me; if we continue to use GAP models to evaluate the force constants for the dislocation, as well as do initial relaxation, then a `LAMMPS`-consistent format seems the best approach, with the scaling into unit cell coordinates for our `VASP` supercell only at the end.

**Comment by aztan2** [comment]
So for scripts interfacing with `LAMMPS`, we're in agreement that scaling out the coordinates doesn't make sense. In terms of reading/writing `POSCAR` files, it is a related but slightly different scaling that is done to get it from/into direct coordinates. As I work through the other issue #2, I'll see how necessary it is to scale out the coordinates by a0 in that case. Maybe it is something we can avoid altogether, or maybe it becomes the exception for that case rather than the rule.
